"""The matrix as Markdown, from what ran: ``python -m tests.matrix.report [junit.xml ...]
[--out build/matrix.md]`` reads the junit files ``make matrix`` writes (one per shard) and
writes feature x adapter x way, feature x mode and the selections, each cell pass, FAIL,
n.a. (with its reason) or xfail (with its gap or bug) — "tested" means it ran: a cell the junit
files do not hold is "not run".

Statuses come from the junit files alone; the tables (``generate.CELLS``) only add each
feature's title, each selection's switches and the order.
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from tests.matrix.dimensions import PENDING, SELECTIONS, SWITCHES, pair_rows
from tests.matrix.generate import CELLS
from tests.matrix.model import ADAPTERS, MODES, WAYS, parse_cell

DEFAULT_JUNIT: Final = Path("build/matrix.xml")
DEFAULT_OUT: Final = Path("build/matrix.md")

PASS, FAIL, NA, XFAIL, NOT_RUN = "pass", "FAIL", "n.a.", "xfail", "not run"


@dataclass(frozen=True)
class Result:
    cell: str
    status: str
    #: the n.a. reason, the gap or bug, or the failure's first line
    detail: str
    seconds: float


def read(paths: Iterable[Path]) -> dict[str, Result]:
    """Every cell's result in the junit files (a later file wins a cell run twice)."""
    found: dict[str, Result] = {}
    for path in paths:
        for case in ET.parse(path).getroot().iter("testcase"):
            name = case.get("name", "")
            if not name.startswith("test_cell[") or parse_cell(name) is None:
                continue
            cell = name.removeprefix("test_cell[").removesuffix("]")
            found[cell] = _result(cell, case)
    return found


def _result(cell: str, case: ET.Element) -> Result:
    seconds = float(case.get("time") or 0)
    failure = case.find("failure")
    if failure is None:
        failure = case.find("error")
    if failure is not None:
        message = (failure.get("message") or failure.text or "").strip().splitlines()
        return Result(cell, FAIL, message[0][:200] if message else "", seconds)
    skipped = case.find("skipped")
    if skipped is not None:
        message = skipped.get("message") or ""
        if skipped.get("type") == "pytest.xfail" or message.startswith("xfail"):
            reason = message.removeprefix("xfail").strip(": ").strip()
            return Result(cell, XFAIL, reason, seconds)
        return Result(cell, NA, message.removeprefix("n.a.: ").strip(), seconds)
    return Result(cell, PASS, "", seconds)


def _summary(results: Sequence[Result]) -> str:
    """One cell of a table: what its results add up to."""
    if not results:
        return NOT_RUN
    counts = Counter(r.status for r in results)
    if counts[FAIL]:
        return f"**FAIL {counts[FAIL]}**/{len(results)}"
    parts = []
    if counts[PASS]:
        parts.append(f"pass {counts[PASS]}")
    gaps = sorted({r.detail.split(":")[0] for r in results if r.status == XFAIL})
    if gaps:
        parts.append(f"xfail {'/'.join(gaps)}")
    if not parts:
        return NA
    return ", ".join(parts)


def render(found: dict[str, Result], seconds: float | None = None) -> str:
    expected = {c.id: c for c in CELLS}
    results = {cid: found.get(cid) for cid in expected}
    ran = [r for r in results.values() if r is not None]
    counts = Counter(r.status for r in ran)
    missing = [cid for cid, r in results.items() if r is None]
    features = list(dict.fromkeys(c.feature.id for c in CELLS))
    titles = {c.feature.id: c.feature.title for c in CELLS}
    by: dict[tuple[str, ...], list[Result]] = defaultdict(list)
    for cid, result in results.items():
        if result is None:
            continue
        feature, adapter, way, mode, selection = parse_cell(cid) or ("",) * 5
        by[("fa", feature, adapter, way)].append(result)
        by[("fm", feature, way, mode)].append(result)
        by[("s", selection, adapter, way)].append(result)
    total = seconds if seconds is not None else sum(r.seconds for r in ran)
    out: list[str] = [
        "# Feature matrix",
        "",
        "Generated by `python -m tests.matrix.report` from the junit results of `make matrix`: "
        "every status below is a test that ran (or was skipped/xfailed with the reason shown).",
        "",
        "## Totals",
        "",
        f"- cells: {len(expected)} ({len(ran)} in the results, {len(missing)} not run)",
        f"- pass: {counts[PASS]}; FAIL: {counts[FAIL]}; xfail (gap or bug): {counts[XFAIL]}; "
        f"n.a.: {counts[NA]}",
        f"- time: {total:.0f}s",
        "",
        "## Dimensions",
        "",
        f"- features: {len(features)} ({', '.join(features)})",
        f"- adapters: {len(ADAPTERS)} ({', '.join(ADAPTERS)})",
        f"- ways: {len(WAYS)} ({', '.join(WAYS)})",
        f"- modes: {len(MODES)} ({', '.join(MODES)})",
        f"- switches: {len(SWITCHES)} ({', '.join(s.id for s in SWITCHES)}); pending: "
        f"{', '.join(f'{p.id} ({p.gap})' for p in PENDING)}",
        f"- selections: {len(SELECTIONS)} (all, none, only.*, without.*, "
        f"{len(pair_rows())} all-pairs rows of which "
        f"{sum(1 for s in SELECTIONS if s.kind == 'pairs')} are new, pending.*)",
        "",
        "Cell values add up the modes and selections of a cell: `pass n` (every one ran and "
        "passed), `xfail G..` (a gap or bug the cell waits on), `n.a.` (see the reasons), "
        "`FAIL n/m`.",
        "",
    ]
    for way in WAYS:
        out += [
            f"## Feature x adapter: {way}",
            "",
            _row(["feature", *ADAPTERS]),
            _rule(len(ADAPTERS) + 1),
        ]
        for feature in features:
            cells = [_summary(by[("fa", feature, a, way)]) for a in ADAPTERS]
            out.append(_row([f"{feature} {titles[feature]}", *cells]))
        out.append("")
    out += ["## Feature x mode (every adapter)", ""]
    for way in WAYS:
        out += [f"### {way}", "", _row(["feature", *MODES]), _rule(len(MODES) + 1)]
        for feature in features:
            out.append(_row([feature, *(_summary(by[("fm", feature, way, m)]) for m in MODES)]))
        out.append("")
    out += ["## Selections (every feature and mode)", ""]
    for way in ("way1", "with_blocks"):
        out += [f"### {way}", "", _row(["selection", "on", *ADAPTERS]), _rule(len(ADAPTERS) + 2)]
        for selection in SELECTIONS:
            on = ", ".join(sorted(selection.on)) if selection.pending is None else "(pending)"
            cells = [_summary(by[("s", selection.id, a, way)]) for a in ADAPTERS]
            if all(c == NOT_RUN for c in cells):
                continue
            out.append(_row([selection.id, on or "-", *cells]))
        out.append("")
    out += _reasons(ran, NA, "Not applicable (reason, cells)")
    out += _reasons(ran, XFAIL, "Waiting on a gap or a bug (xfail strict: id, cells)")
    failed = sorted((r for r in ran if r.status == FAIL), key=lambda r: r.cell)
    out += ["## Failures", ""]
    out += [f"- `{r.cell}`: {r.detail}" for r in failed] or ["none"]
    out.append("")
    if missing:
        out += ["## Not run", "", *(f"- `{cid}`" for cid in missing[:200])]
        if len(missing) > 200:
            out.append(f"- ... and {len(missing) - 200} more")
        out.append("")
    return "\n".join(out)


def _reasons(ran: Sequence[Result], status: str, title: str) -> list[str]:
    counts = Counter(r.detail for r in ran if r.status == status)
    lines = [f"## {title}", ""]
    lines += [f"- {reason or '(none given)'}: {n}" for reason, n in counts.most_common()]
    return [*lines, ""]


def _row(cells: Sequence[str]) -> str:
    return "| " + " | ".join(c.replace("|", "/") for c in cells) + " |"


def _rule(n: int) -> str:
    return "|" + "---|" * n


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m tests.matrix.report", description=__doc__)
    parser.add_argument(
        "junit", nargs="*", type=Path, help=f"junit files (default {DEFAULT_JUNIT})"
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)
    paths = args.junit or sorted(DEFAULT_JUNIT.parent.glob("matrix*.xml"))
    if not paths:
        print(f"no junit results: run make matrix first ({DEFAULT_JUNIT})", file=sys.stderr)
        return 2
    seconds = sum(
        float(s.get("time") or 0) for p in paths for s in ET.parse(p).getroot().iter("testsuite")
    )
    text = render(read(paths), seconds)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
